#!/usr/bin/env bash
#
# Run all checks and tests
#

set -eu

echo "Running clippy checks..."

for profile in dev release; do
    cargo clippy --workspace --all-targets --all-features --no-deps --profile "$profile" -- -Dwarnings
done

echo -e "\nRunning tests..."
cargo test